# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'error.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_errorwindow(object):

    def openlogin(self):
        from login2 import Ui_loginWindow
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_loginWindow(self.window)
        self.ui.setupUi()
        self.window.show()

    def setupUi(self, errorwindow):
        errorwindow.setObjectName("errorwindow")
        errorwindow.resize(500, 232)
        self.centralwidget = QtWidgets.QWidget(errorwindow)
        self.centralwidget.setStyleSheet("QPushButton#back_Button{\n"
"    background-color: rgb(194, 151, 125);\n"
"    \n"
"    \n"
"    border-left:1px solid rgb(255,76,100);\n"
"    border-right:1px solid rgb(255,76,100);\n"
"    border-bottom:5px solid rgb(255,76,100);\n"
"}\n"
"QPushButton#back_Button:hover{\n"
"    background-color:rgb(192,192,192);\n"
"    color:rgb(0,0,0);\n"
"    border-left:1px solid rgb(128,128,128);\n"
"    border-right:1px solid rgb(128,128,128);\n"
"    border-bottom:5px solid rgb(128,128,128);\n"
"}\n"
"QPushButton#back_Button:pressed{\n"
"    background-color:rgb(192,192,192);\n"
"    color:rgb(0,0,0);\n"
"    border-left:1px solid rgb(128,128,128);\n"
"    border-right:1px solid rgb(128,128,128);\n"
"    border-top:5px solid rgb(128,128,128);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 500, 230))
        self.label_2.setStyleSheet("\n"
"background-color: rgb(115, 192, 136);")
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setLineWidth(5)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 30, 431, 41))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(160, 80, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.back_Button = QtWidgets.QPushButton(self.centralwidget)
        self.back_Button.setGeometry(QtCore.QRect(140, 170, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.back_Button.setFont(font)
        self.back_Button.setObjectName("back_Button")
        errorwindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(errorwindow)
        QtCore.QMetaObject.connectSlotsByName(errorwindow)
        self.back_Button.clicked.connect(errorwindow.close)

    def retranslateUi(self, errorwindow):
        _translate = QtCore.QCoreApplication.translate
        errorwindow.setWindowTitle(_translate("errorwindow", "MainWindow"))
        self.label.setText(_translate("errorwindow", "Your Student ID or Password is wrong"))
        self.label_3.setText(_translate("errorwindow", "Please check again"))
        self.back_Button.setText(_translate("errorwindow", "back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    errorwindow = QtWidgets.QMainWindow()
    ui = Ui_errorwindow()
    ui.setupUi(errorwindow)
    errorwindow.show()
    sys.exit(app.exec_())
