# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from predic import PredicData
from takePhoto import TakePhoto
from points2 import Ui_pointWindow
import pandas as pd
import openpyxl
#from login2 import Ui_loginWindow

class Ui_MainWindow(object):
    def __init__(self,student_id, getIndex) -> None:
        self.student = student_id
        self.index = getIndex
        self.point_set = 0
        
    def openpoints(self):
        self.point_set = self.read_point()
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_pointWindow(points = self.point_set )
        self.ui.setupUi(self.window)
        self.window.show()
        
    def openlogin(self):
        from login2 import Ui_loginWindow
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_loginWindow(self.window)
        self.ui.setupUi()
        self.window.show()
        
        
        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(492, 233)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QPushButton#Logout_Button{\n"
"    background-color: rgb(194, 151, 125);\n"
"    \n"
"    \n"
"    border-left:1px solid rgb(255,76,100);\n"
"    border-right:1px solid rgb(255,76,100);\n"
"    border-bottom:5px solid rgb(255,76,100);\n"
"}\n"
"QPushButton#Logout_Button:hover{\n"
"    background-color:rgb(192,192,192);\n"
"    color:rgb(0,0,0);\n"
"    border-left:1px solid rgb(128,128,128);\n"
"    border-right:1px solid rgb(128,128,128);\n"
"    border-bottom:5px solid rgb(128,128,128);\n"
"}\n"
"QPushButton#Logout_Button:pressed{\n"
"    background-color:rgb(192,192,192);\n"
"    color:rgb(0,0,0);\n"
"    border-left:1px solid rgb(128,128,128);\n"
"    border-right:1px solid rgb(128,128,128);\n"
"    border-top:5px solid rgb(128,128,128);\n"
"}\n"
"QPushButton#ViewPoint_Button{\n"
"    background-color: rgb(153, 184, 152);\n"
"    \n"
"    \n"
"    border-left:1px solid rgb(255,76,100);\n"
"    border-right:1px solid rgb(255,76,100);\n"
"    border-bottom:5px solid rgb(255,76,100);\n"
"}\n"
"QPushButton#ViewPoint_Button:hover{\n"
"    background-color:rgb(192,192,192);\n"
"    color:rgb(0,0,0);\n"
"    border-left:1px solid rgb(128,128,128);\n"
"    border-right:1px solid rgb(128,128,128);\n"
"    border-bottom:5px solid rgb(128,128,128);\n"
"}\n"
"QPushButton#ViewPoint_Button:pressed{\n"
"    background-color:rgb(192,192,192);\n"
"    color:rgb(0,0,0);\n"
"    border-left:1px solid rgb(128,128,128);\n"
"    border-right:1px solid rgb(128,128,128);\n"
"    border-top:5px solid rgb(128,128,128);\n"
"}\n"
"QPushButton#ready_button{\n"
"    background-color: rgb(153, 184, 152);\n"
"    \n"
"    \n"
"    border-left:1px solid rgb(255,76,100);\n"
"    border-right:1px solid rgb(255,76,100);\n"
"    border-bottom:5px solid rgb(255,76,100);\n"
"}\n"
"QPushButton#ready_button:hover{\n"
"    background-color:rgb(192,192,192);\n"
"    color:rgb(0,0,0);\n"
"    border-left:1px solid rgb(128,128,128);\n"
"    border-right:1px solid rgb(128,128,128);\n"
"    border-bottom:5px solid rgb(128,128,128);\n"
"}\n"
"QPushButton#ready_button:pressed{\n"
"    background-color:rgb(192,192,192);\n"
"    color:rgb(0,0,0);\n"
"    border-left:1px solid rgb(128,128,128);\n"
"    border-right:1px solid rgb(128,128,128);\n"
"    border-top:5px solid rgb(128,128,128);\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 250, 230))
        self.label_2.setStyleSheet("\n"
"background-color: rgb(123, 174, 106);")
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setLineWidth(5)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(240, 0, 250, 230))
        self.label_3.setStyleSheet("background-color: rgb(116, 146, 122);")
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setLineWidth(5)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.Student_ID_2 = QtWidgets.QLabel(self.centralwidget)
        self.Student_ID_2.setGeometry(QtCore.QRect(10, 10, 221, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Student_ID_2.setFont(font)
        self.Student_ID_2.setStyleSheet("background-color: rgb(0,0,0,0);\n"
"\n"
"\n"
"border-bottom:2px solid rgba(46,82,101,200);")
        self.Student_ID_2.setObjectName("Student_ID_2")
        self.Logout_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Logout_Button.setGeometry(QtCore.QRect(40, 180, 161, 28))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Logout_Button.setFont(font)
        self.Logout_Button.setObjectName("Logout_Button")
        self.ViewPoint_Button = QtWidgets.QPushButton(self.centralwidget)
        self.ViewPoint_Button.setGeometry(QtCore.QRect(20, 70, 201, 81))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.ViewPoint_Button.setFont(font)
        self.ViewPoint_Button.setObjectName("ViewPoint_Button")
        self.ready_button = QtWidgets.QPushButton(self.centralwidget)
        self.ready_button.setGeometry(QtCore.QRect(260, 30, 211, 40))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ready_button.setFont(font)
        self.ready_button.setObjectName("ready_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 100, 191, 101))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.ViewPoint_Button.clicked.connect(self.openpoints)
        self.Logout_Button.clicked.connect(self.openlogin)
        self.Logout_Button.clicked.connect(MainWindow.close)
        self.ready_button.clicked.connect(self.checkBottle)

    def checkBottle(self):
        # readyToCap = TakePhoto()
        # getModel = PredicData()
        # readyToCap.takePicture()
        print("In progress....")
        # self.getLabel = getModel.sendData()
        if "Bottle_Ready" == "Bottle_Ready3":
            # print(self.getLabel)
            data_df = self.read_point()
            wd = openpyxl.load_workbook("studentData.xlsx")
            ws = wd['Sheet1']
            ws.cell(row=self.index+2,column=3).value = int(data_df)+3
            wd.save("studentData.xlsx")
            _translate = QtCore.QCoreApplication.translate
            self.label.setText(_translate("MainWindow", "Congratulations !!!\n"
"You get the points "))
            print(data_df)
        else:
            _translate = QtCore.QCoreApplication.translate
            self.label.setText(_translate("MainWindow", "กรุณาแกะพลาสติกข้างๆ\nออกด้วย !!!"))
            # print(self.getLabel)
            print("Error")

    def read_point(self):
        excel_data_df = pd.read_excel('studentData.xlsx')
        x = excel_data_df.loc[self.index, ['Point']]
        return x
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Student_ID_2.setText(_translate("MainWindow", self.student))
        self.Logout_Button.setText(_translate("MainWindow", "L o g O u t"))
        self.ViewPoint_Button.setText(_translate("MainWindow", "View Point"))
        self.ready_button.setText(_translate("MainWindow", "Ready"))
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())